### PR TITLE
Enable sanity.functional and dev.external on machines with criu318

### PR DESCRIPTION
**Pull request by llxia**
related: runtimes/backlog/issues/1099

### CODE REVIEW

**Comment by llxia** [comment]
@AdamBrousseau could you review the PR? Thanks

**Review by AdamBrousseau — APPROVED** [review]
lftm but I don't believe we currently run these ppc criu specs by default in any build. We'll have to make another change in jdk11u.groovy and jdk17u.groovy if we want to turn them on as well as in the job generator I believe.

**Comment by llxia** [comment]
I noticed [jdk11u-linux-ppc64le-openj9-criu](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-openj9-criu/) and [jdk17u-linux-ppc64le-openj9-criu](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-linux-ppc64le-openj9-criu/). Can we use them? If jdk11u.groovy and jdk17u.groovy needs to be updated, could you help? Thanks

**Comment by llxia** [comment]
We should not block the change related to the test builds because jdk11u.groovy and jdk17u.groovy are not ready. If jdk11u.groovy and jdk17u.groovy needs to be updated, we can create separate PR.

**Review by AdamBrousseau — CHANGES_REQUESTED** [review]
I think this can be updated. All machines are at 3.18 now so we don't need to add the extra label.

**Comment by AdamBrousseau** [comment]
As discussed, we can move the `dev.external` additional target to the regular IBM (CE) plinux specs.

**Comment by llxia** [comment]
This PR is no longer needed as CRIU is enabled as default on plinux and we do not need criu318 label anymore.

**Pull request closed without merging**
