### PR TITLE
setting sdk_resource as customized for runAqaTest

### PR DESCRIPTION
**Pull request by julian55455**
Fixes https://github.com/adoptium/aqa-tests/issues/2097

cc @llxia @sophia-guo @smlambert

### CODE REVIEW

**Review by llxia — APPROVED** [review]
LGTM. I think we should merge it after the release.

**Comment by smlambert** [comment]
Yes we are in a code freeze right now so this will not get merged for a bit.  @julian55455 you can still mark it as a Outreachy contribution despite the delay to merge it.

**Comment by sophia-guo** [comment]
This PR is dependent PR of https://github.com/adoptium/aqa-tests/issues/2097, which will not fix https://github.com/adoptium/aqa-tests/issues/2097. Might be better to update the description to related instead of fix https://github.com/adoptium/aqa-tests/issues/2097

**Comment by llxia** [comment]
@julian55455 could you please update the description as suggested in https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/108#issuecomment-1284285148? Thanks

**Comment by AdamBrousseau** [comment]
Is there a reason why we aren't delivering this upstream to the main Adopt repo?

**Comment by llxia** [comment]
Adopt uses `upstream` as they use staged SDK on Jenkins. Semeru pipeline uses `customized` (SDK URL from artifactory). This is a special case for Semeru.

**Comment by AdamBrousseau** [comment]
Got it, thanks.

**Comment by llxia** [comment]
@AdamBrousseau could you please review this PR? Thanks

**Review by AdamBrousseau — APPROVED** [review]

**Pull request merged**
