### PR TITLE
Disable xlinux criu spec

### PR DESCRIPTION
**Pull request by AdamBrousseau**
CRIU now enabled by default

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@tajila please confirm

**Comment by tajila** [comment]
Yes, please disable the xlinux criu spec

**Comment by tajila** [comment]
Do we need to disable the jobs first https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-CRIU/239/ ?

**Comment by AdamBrousseau** [comment]
Separate jobs/code but I also removed it from that build schedule.

**Pull request merged**
