### PR TITLE
AArch64 macOS: Enable DDR builds

### PR DESCRIPTION
**Pull request by knn-k**
This commit removes the "--disable-ddr" option from configuration for AArch64 macOS.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Related PR: https://github.com/eclipse-openj9/openj9/pull/14420

**Review by AdamBrousseau — APPROVED** [review]
lgtm, let me know when you want to merge.

**Comment by knn-k** [comment]
I can enable DDR in my local environment, but I found a toolchain problem on build servers: https://github.com/eclipse/omr/issues/6491

**Comment by knn-k** [comment]
I am going to change the status of this PR to "ready for review" when https://github.com/eclipse/omr/pull/5800 gets merged.

**Comment by knn-k** [comment]
Waiting for https://github.com/eclipse/omr/pull/6527 to promote.

**Comment by knn-k** [comment]
Rebased.

**Comment by knn-k** [comment]
@AdamBrousseau  This PR is ready now.

**Comment by knn-k** [comment]
AArch64 macOS DDR build is now enabled for OpenJ9 Jenkins by https://github.com/eclipse-openj9/openj9/pull/14420.
DDR tests are also enabled.

**Review by AdamBrousseau — CHANGES_REQUESTED** [review]
Please update `jdk19_pipeline_config.groovy` as well.

**Comment by knn-k** [comment]
I updated jdk19_pipeline_config.groovy.

**Review by AdamBrousseau — APPROVED** [review]
Thanks @knn-k

**Pull request merged**
